### ISSUE TITLE
Not updating password

### ISSUE THREAD

**Issue by JobaDiniz** [rejeep/authlogic-password-reset-tutorial#2]
It isn't updating the password.
Everything works except the update of password.
It sends an email with the url. Here's go the log from the console:
Any help?

```
Processing PasswordResetsController#update (for 127.0.0.1 at 2010-08-23 11:04:05) [PUT]
  Parameters: {"commit"=>"Atualizar", "action"=>"update", "_method"=>"put", "authenticity_token"=>"PM0h4a4wwqRp+VMMcnGIzvMf9tV9bPS5mtcMZwCwQWI=", "id"=>"6WBLhSGcdmenvdZyZND", "controller"=>"password_resets", "password"=>"[FILTERED]"}
  User Columns (7.5ms)   SHOW FIELDS FROM `users`
  User Load (2.1ms)   SELECT * FROM `users` WHERE (perishable_token = '6WBLhSGcdmenvdZyZND' and updated_at > '2010-08-23 13:54:05') LIMIT 1
  SQL (0.8ms)   BEGIN
  User Load (2.3ms)   SELECT `users`.id FROM `users` WHERE (`users`.`persistence_token` = BINARY 'b6371f37efeb7242514382445198d8558d222d09e29b2eee336b0487d9ec75fc97b669a11228d66359a4097af258cb493ad2e1594c8b845b941c25b4542bb1e4' AND `users`.id <> 3) LIMIT 1
  User Load (0.9ms)   SELECT `users`.id FROM `users` WHERE (`users`.`login` = BINARY 'joba' AND `users`.id <> 3) LIMIT 1
  User Load (1.8ms)   SELECT `users`.id FROM `users` WHERE (`users`.`email` = BINARY 'jobertodinizjunior@gmail.com' AND `users`.id <> 3) LIMIT 1
  SQL (2.0ms)   ROLLBACK
Rendering template within layouts/application
Rendering password_resets/edit
Rendered layouts/_header (18.8ms)
Completed in 123ms (View: 27, DB: 18) | 200 OK [http://localhost/senha/6WBLhSGcdmenvdZyZND]
```

**Comment by rejeep** [comment]
From the update action, you are being redirected to edit. This means that the user could not be saved. Can you change you update action to this and post the output log?

```
def update
  @user.password = params[:password]
  p '###########################'
  p @user.valid?
  p @user.errors
  p '###########################'
  if @user.save
    flash[:success] = "Your password was successfully updated"
    redirect_to @user
  else
    render :action => :edit
  end
end
```

**Comment by JobaDiniz** [comment]
"###########################"
false
#<ActiveRecord::Errors:0xb7014e58 @base=#<User id: 3, nome: "joberto", sobrenome: "diniz", login: "joba", excluido: nil, avatar_cortado: nil, nascimento: "2010-08-23", email: "jobertodinizjunior@gmail.com", cidade_id: 5074, estado_id: 16, crypted_password: "a1cd337d28c4912e4b8b000a1904ae96256ba68c31b9ffedd07...", password_salt: "83KyX7YN2D1nf2isVe6S", persistence_token: "a6cd60c3a912750fd59aa5f99fa40a12d7aac092629884b47cc...", perishable_token: "6m8JN2iwl1fLKcigd0", login_count: 3, failed_login_count: 0, last_request_at: "2010-08-23 14:50:43", current_login_at: "2010-08-23 14:11:57", last_login_at: "2010-08-23 14:10:09", current_login_ip: "127.0.0.1", last_login_ip: "127.0.0.1", created_at: "2010-08-23 13:43:48", updated_at: "2010-08-23 14:50:53", avatar_file_name: "bellacapri.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 45575, avatar_updated_at: "2010-08-23 13:43:46", active: true>, @errors=#<OrderedHash {"password_confirmation"=>[#<ActiveRecord::Error:0xb7012428 @base=#<User id: 3, nome: "joberto", sobrenome: "diniz", login: "joba", excluido: nil, avatar_cortado: nil, nascimento: "2010-08-23", email: "jobertodinizjunior@gmail.com", cidade_id: 5074, estado_id: 16, crypted_password: "a1cd337d28c4912e4b8b000a1904ae96256ba68c31b9ffedd07...", password_salt: "83KyX7YN2D1nf2isVe6S", persistence_token: "a6cd60c3a912750fd59aa5f99fa40a12d7aac092629884b47cc...", perishable_token: "6m8JN2iwl1fLKcigd0", login_count: 3, failed_login_count: 0, last_request_at: "2010-08-23 14:50:43", current_login_at: "2010-08-23 14:11:57", last_login_at: "2010-08-23 14:10:09", current_login_ip: "127.0.0.1", last_login_ip: "127.0.0.1", created_at: "2010-08-23 13:43:48", updated_at: "2010-08-23 14:50:53", avatar_file_name: "bellacapri.jpg", avatar_content_type: "image/jpeg", avatar_file_size: 45575, avatar_updated_at: "2010-08-23 13:43:46", active: true>, @options={:count=>4, :default=>nil}, @attribute=:password_confirmation, @message=:too_short, @type=:too_short>]}>>
"###########################"

**Comment by JobaDiniz** [comment]
How do I post as code snippet?

**Comment by rejeep** [comment]
If you put four (4) spaces before each line, your text will be considered code. Read more here: http://github.github.com/github-flavored-markdown/

It was really hard to read your output. But it seems like you have activated password confirmation in Authlogic?

I'm not sure since I haven't used that myself. But maybe you have to set that aswell? Try:
    def update
      @user.password = params[:password]
      @user.password_confirmation = params[:password]
      p '###########################'
      p @user.valid?
      p @user.errors.to_json
      p '###########################'
      if @user.save
        flash[:success] = "Your password was successfully updated"
        redirect_to @user
      else
        render :action => :edit
      end
    end

**Comment by JobaDiniz** [comment]
yeah... you're right. Thanks.

**Comment by rejeep** [comment]
I added it in the tutorial, just to be clear.

http://github.com/rejeep/authlogic-password-reset-tutorial/commit/fa4b1014323f260482ded7a296abf7e78dab53ec
