### ISSUE TITLE
Auto logging in after resetting pw

### ISSUE THREAD

**Issue by wejrowski** [rejeep/authlogic-password-reset-tutorial#4]
Everything works great, but when goto the link and reset the password, I'm now logged in as that user. I like that it's doing that, but I'm a bit concerned why and where it's doing that. I can't seem to track it down. 

Any ideas? It seems to happen after I save and forward the user in the update action.

**Comment by rejeep** [comment]
Hey,

Quite some time ago I looked at this code, so I'm not sure. And like you, I can not see any "sign in" being done.

Are you sure the user is signed in? I can see redirection is done to @user, so it would make sense. But can you try to print `current_user` after reset to make sure it is set?

If the user is signed in, that would be something Authlogic does automatically somehow.

**Comment by wejrowski** [comment]
yeah I was doing some prints all over the place and the current_user at least wasn't showing up before the redirect. When I get to the new controller though it's set. Kinda strange.

**Comment by rejeep** [comment]
I'm thinking Authlogic hooks into `ActiveRecord#save` somehow and automatically sign in the user. There's another method used to skip session maintenance (see https://github.com/binarylogic/authlogic/blob/master/lib/authlogic/acts_as_authentic/session_maintenance.rb#L71).

Can you change `save` to `save_without_session_maintenance` and see if that will sign in the user or not?

**Comment by wejrowski** [comment]
ah that was exactly it. I was wondering if it did something like that.

Thanks!

**Comment by rejeep** [comment]
Talk about violation of [POLA](http://en.wikipedia.org/wiki/Principle_of_least_astonishment). I added a note about it in the source. See https://github.com/rejeep/authlogic-password-reset-tutorial/commit/d556d130ae5466fd46e6ec5b9002d1de3d57f0cc

**Comment by wejrowski** [comment]
Yeah it is strange. You would think that they would first check to see if there is a session with a user logged in. If not.. don't create one!
