### ISSUE TITLE
ERB new view doesn't display form

### ISSUE THREAD

**Issue by saulcosta** [rejeep/authlogic-password-reset-tutorial#6]
I think you are missing an '=' in the form_tag... should be 

<%= form_tag password_resets_path do %>

not 

<% form_tag password_resets_path do %>

At least that's what works for me.

**Comment by rejeep** [comment]
Thanks, fixed in https://github.com/rejeep/authlogic-password-reset-tutorial/commit/12b651c3b774c696576289192e9c1a1646328d2b. When I wrote this Rails didn't used the `<%=` syntax.
